# data types

In [ ]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# S - string


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
# print(type(a))
print(a.dtype)
a

int64


array([1, 2, 3, 4])

In [2]:
a = np.array(["ab","ju8","979kjui8yhi"])

print(a.dtype)



#U: Represents a Unicode string data type in NumPy.
#3: Indicates the maximum length of each string in the array, in terms of Unicode characters.

<U11


In [4]:
a = np.array([2.7,9.0])

print(a.dtype)

float64


In [6]:
a = np.array([1+3j])

print(a.dtype)

complex128


In [11]:
c=np.array([1,2,3,476],dtype='S')
print(c)
# print(c.dtype)
# type
#byte strings

[b'1' b'2' b'3' b'476']


In [15]:
# i8 mention size
a = np.array([1, 2, 3, 4], dtype='i4')

print(a)
print(a.dtype)

[1 2 3 4]
int32


In [17]:
#connot change integer

a = np.array(['1', '2', '3'], dtype='i2')
a

array([1, 2, 3], dtype=int16)

In [ ]:
a = np.array(['a', 'juookk882', '33893'], dtype='S')
print(a)
print(a.dtype)

In [ ]:
a = np.array(['1', '2', '3'], dtype='i8')
print(a)
print(a.dtype)

In [5]:
b=a.astype("S")
b

array([b'2.7', b'9.0'], dtype='|S32')

In [6]:
newa = np.array([1.1, 2.1, 3.1])

newarr = newa.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [7]:
newa = np.array(["1", "2", "3"])

newarr = newa.astype("i8")

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [8]:
newa = np.array([1, 0, 3])

newarr = newa.astype(bool)

print(newarr)

print(newarr.dtype)

[ True False  True]
bool


# Copy and view

In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5,8,10])

x = a.copy()
x[0] = 42

print(a)
print(x)

[ 1  2  3  4  5  8 10]
[42  2  3  4  5  8 10]


In [10]:
a = np.array([1, 2, 3, 4, 5])
x = a.view()
x[0] = 42

print(a)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [11]:

import numpy as np

# Arrays
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4, 5, 6],[1, 2, 3]])

# Operations
addition = a + b         # [5, 7, 9]
subtraction = a - b      # [-3, -3, -3]
multiplication = a * b   # [4, 10, 18]
division = a / b         # [0.25, 0.4, 0.5]

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [[5 7 9]
 [2 4 6]]
Subtraction: [[-3 -3 -3]
 [ 0  0  0]]
Multiplication: [[ 4 10 18]
 [ 1  4  9]]
Division: [[0.25 0.4  0.5 ]
 [1.   1.   1.  ]]


In [12]:
a=[1,3,4,7]
b=[3,4,5,9,10]
for k in range (len(a)):
    print(a[k]+b[k])

4
7
9
16


In [13]:
a=np.array([1,2,3])
b=np.array([3,4,5])
a/b   

array([0.33333333, 0.5       , 0.6       ])

In [14]:
def add(A,b):
    return A+b

add(6,7)

13

In [15]:
class Animal:
    def __init__(self, breed):
        self.name = breed
        print(f"Animal initialized with name: {self.name}")

class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(breed)  # calls Animal's __init__
        self.breed = breed
        print(f"Dog initialized with breed: {self.breed}")

d = Dog("Tommy", "Labrador")


Animal initialized with name: Labrador
Dog initialized with breed: Labrador
